
name: ZAP Baseline
permissions:
  contents: read
  actions: read
  security-events: read

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest # The runner where the job executes
    steps:
      - run: docker run -t owasp/zap2docker-stable zap-baseline.py \
            -t http://yourapp.local \
            -r zap-report.html
