name: Secure Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  sast:
    runs-on: ubuntu-latest # The runner where the job executes
    steps:
      - uses: actions/checkout@v3
      - run: semgrep --config auto --json > semgrep-report.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

  sca:
    runs-on: ubuntu-latest # The runner where the job executes
    steps:
      - run: trivy fs .

  dast:
    runs-on: ubuntu-latest # The runner where the job executes
    needs: [ sast, sca ]
    steps:
      - run: docker run -t owasp/zap2docker-stable zap-baseline.py -t http://yourapp.local
